ALTER TABLE CONTACTO DROP CONSTRAINT CONTACTOpersona_id
ALTER TABLE CONTACTO DROP CONSTRAINT CONTACTO_UNIDAD_ID
ALTER TABLE UNIDAD DROP CONSTRAINT NIDADunidadpadreid
ALTER TABLE UNIDAD DROP CONSTRAINT UNIDAD_empresa_id
ALTER TABLE EMPRESA DROP CONSTRAINT MPRSAmpresapadreid
ALTER TABLE COMUNA DROP CONSTRAINT CMNcmnaprovinciaid
ALTER TABLE PROVINCIA DROP CONSTRAINT PRVNCprvncregionid
ALTER TABLE DIRECCION DROP CONSTRAINT DRCCIONRGNregionid
ALTER TABLE DIRECCION DROP CONSTRAINT DRCCIONCMNcomunaid
ALTER TABLE EDIFICIO DROP CONSTRAINT DFICIOPRPIETARIOID
ALTER TABLE EDIFICIO DROP CONSTRAINT DIFICIODIRECCIONID
ALTER TABLE EDIFICIO DROP CONSTRAINT DIFICIODRECTORIOID
ALTER TABLE EDIFICIO DROP CONSTRAINT EDIFICIOcliente_id
ALTER TABLE CLIENTE DROP CONSTRAINT CLIENTE_EMPRESA_ID
ALTER TABLE CLIENTE DROP CONSTRAINT CLNTMPRSFACTURARID
ALTER TABLE USUARIO DROP CONSTRAINT USUARIOCONTACTO_ID
ALTER TABLE DEPENDENCIA DROP CONSTRAINT DPENDENCIADFICIOID
ALTER TABLE DEPENDENCIA DROP CONSTRAINT DPNDNCdpndncpdreid
ALTER TABLE DEPENDENCIA DROP CONSTRAINT DPNDNCASRNMUEBLEID
ALTER TABLE RESERVA DROP CONSTRAINT RSERVADPENDENCIAID
ALTER TABLE RESERVA DROP CONSTRAINT RESERVA_EMISOR_ID
ALTER TABLE RESERVA DROP CONSTRAINT RESERVA_VISITA_ID
ALTER TABLE ACCESO DROP CONSTRAINT ACCESOANFITRION_ID
ALTER TABLE ACCESO DROP CONSTRAINT ACCESO_VISITA_ID
ALTER TABLE ACCESO DROP CONSTRAINT CCESODEPENDENCIAID
ALTER TABLE USUARIOINMUEBLE DROP CONSTRAINT SROINMUEBLEMPRSAID
ALTER TABLE USUARIOINMUEBLE DROP CONSTRAINT SRNMUEBLEDRCTRIOID
ALTER TABLE CLIENTE_APLICACION DROP CONSTRAINT CLNTPLICACIONCLNTD
ALTER TABLE CLIENTE_APLICACION DROP CONSTRAINT CLNTPLCCIONPLCCNSD
ALTER TABLE CLIENTE_USUARIO DROP CONSTRAINT CLNTEUSUARIOsrosID
ALTER TABLE CLIENTE_USUARIO DROP CONSTRAINT CLNTUSUARIOClnteID
ALTER TABLE USUARIO_ROL DROP CONSTRAINT SUARIOROLUSUARIOID
ALTER TABLE USUARIO_ROL DROP CONSTRAINT USUARIOROLROLES_ID
ALTER TABLE ROL_USUARIO DROP CONSTRAINT ROL_USUARIO_ROL_ID
ALTER TABLE ROL_USUARIO DROP CONSTRAINT RLUSUARIOSUARIOSID
ALTER TABLE APLICACION_CLIENTE DROP CONSTRAINT PLCCNCLIENTECLNTSD
ALTER TABLE APLICACION_CLIENTE DROP CONSTRAINT PLCCNCLIENTEPLCCND
DROP TABLE PERSONA
DROP TABLE CONTACTO
DROP TABLE UNIDAD
DROP TABLE EMPRESA
DROP TABLE COMUNA
DROP TABLE PROVINCIA
DROP TABLE REGION
DROP TABLE DIRECCION
DROP TABLE EDIFICIO
DROP TABLE CLIENTE
DROP TABLE USUARIO
DROP TABLE ROL
DROP TABLE APLICACION
DROP TABLE DEPENDENCIA
DROP TABLE RESERVA
DROP TABLE ACCESO
DROP TABLE DIRECTORIO
DROP TABLE USUARIOINMUEBLE
DROP TABLE CLIENTE_APLICACION
DROP TABLE CLIENTE_USUARIO
DROP TABLE USUARIO_ROL
DROP TABLE ROL_USUARIO
DROP TABLE APLICACION_CLIENTE
